name: ArxivDigest Daily

on:
  schedule:
    - cron: '0 23 * * *'   # UTC 23:00 → 日本時間 AM8:00 頃に実行
  workflow_dispatch:        # 手動実行ボタンも有効化

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ArxivDigest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: |
          python src/action.py
